ifndef::ver[]
:ver: 1.1.3
endif::[]
:sillyName: Memory Lane
ifndef::current-java-ver[]
:current-java-ver: Java 21
endif::[]
:gh-url: https://github.com/IanDarwin/pdfshow
:releases-link: {gh-url}/releases
:download-link: {releases-link}/download/v{ver}

= PdfShow Version {ver} ("{sillyName}")

`PdfShow` is a PDF viewer specifically for running slide shows.
I wrote it because I sometimes teach from PDFs and was tired of general-purpose programs 
like PDF Annotator and Adobe Reader, which have too many modes,
controls, etc. and aren't really optimized for showing slide decks.

Wait! Who presents from PDFs?
https://darwinsys.com/pdfshow[Lots of people. See the website].

`PdfShow` has fewer features than other tools, due to
its relative youth and, more importantly, its design goals.
_Please_ see the https://github.com/IanDarwin/pdfshow/issues[list of issues];
read through it before condemning the app as incomplete and again before
adding to it - anyone can create a free github account and add issues there!
That is also why there's no TODO file here - all the TODOs are in the issues list.

The program is for desktops, not mobiles. There is too much dependency on Swing
to make it feasible to run on platforms other than desktop Java.

You can have multiple documents open, which show in the expected tab-vew format.
You can drag the tabs around, e.g., to move the most important ones to the left (or right)
or for any sort of ordering that makes sense to you at the time.

`PdfShow` supports dual monitors, one for control and one for viewing slides.
As of now, the control window will appear on Monitor 1 and the view on Monitor 2;
someday that'll be switchable via an option.

* You can't draw on the miniature view (yet?), and it doesn't show your drawings.
* If you unplug the second monitor, you have to re-start PDFshow, but that shouldn't be a problem.

More bells and whistles will likely be added as time permits, but let's keep it relatively simple.
There is still some basic functionality that is imperfect or incomplete.
Pull requests will be gratefully accepted as long as they fit
within the general tone of the program - _minimalist, but functional._

== Recent Changes

1.1.3 You can save, and later restore, all your annotations (in the current tab only).

1.1.2 You can add smileys, checkmarks and X/fail marks.

1.1.1 Adds the ability to modify, copy/paste, or edit a text annotation.  Numerous small fixes.

== Installing PdfShow

[[installation-summary]]
.Installation/Download Summary
[options="header",cols="2,2,5,5"]
|====
|OS|Pkg Format|CLI Install|Install Download
|Java|fat jar|n/a/|{download-link}/pdfshow-{ver}-jar-with-dependencies.jar
|Linux|deb|Download then install|{download-link}/pdfshow_{ver}_amd64.deb
|Linux|rpm|Download then dnf install|{download-link}/pdfshow-{ver}-1.x86_64.rpm
|macOS|dmg|Download; should open|{download-link}/PDFShow-{ver}.dmg
|Windows|msi|Download and click on|{download-link}/PDFShow-{ver}.msi
|====

(Winget does not currently install the latest version, sorry.)

Or check the {releases-link}[latest release under the _Assets_ dropdown].

The installers bundle their own Java VM, with which they are known
to work; they are about 50Mb to download and about 120-140Mb when installed.
If you already have a current Java installed, you may prefer to run the `jar-with-dependencies` file; you have to be sure
you have a JDK that will work with `PdfShow`.
This JAR is usually built with {current-java-ver} or later.

For MS-Windows, assuming the `winget` db is update-to-date (which it often is), just type this in a terminal window:

	winget install RejminetGroupInc.PDFShow

(That's really me; Rejminet Group Inc. is my consulting company.)

Windows users can also download the .msi and click on it to start the install.

Finally, if there's no installer for you, but you have Java,
there's a Jar file that you can run with `java -jar`.

If you want to try building it from source, see the file link:docs/building-from-source.adoc[].

== Using PdfShow

"It is intuitively obvious", but see https://darwinsys.com/pdfshow/#using_pdfshow[the web site].

== Credits

Program written by Ian Darwin of Rejminet Group Inc.
Contributions by a cast of thousands (we hope).
For now, the main other contributor is Marc Loy.
All contributors' names are listed on the main github page.
Thanks In Advance, folks!

Draggable Tab component DnDTabbedPane courtesy of
https://java-swing-tips.blogspot.com/2008/04/drag-and-drop-tabs-in-jtabbedpane.html

PDF access (i.e., some of the heavy listing!) is done by
https://pdfbox.apache.org/[Apache PDFBox] software.

Icons from feathericons.com, OpenClipArt, and Ian Darwin.
Stock images for breaktimer created by an AI.
