= PdfShow

PdfShow is a simple Java Swing-based PDF viewer specifically for running slide shows.

It has many limitations compared with other tools (see the 
https://github.com/IanDarwin/pdfshow/issues[TODO list]), due to 
its relative youth and, more importantly, its design goals.
These are laid out in the User Guide.

We will add more bells and whistles as time permits.

Pull requests will be gratefully accepted as long as they fit
within the general tone of the program - _minimalist, but functional._ 

== Using It

The program is intuitive and easy to use.
But there is documentation, in the `docs` folder.

== Build It

Download the repository from https://github.com/IanDarwin/pdfshow.

Copy the file pdfshow.properties.sample to pdfshow.properties, and edit as per the comments.
*If you miss this step, you will get obscure errors like "Cannot start JVM"!*.

There is a Maven dependency on darwinsys-api; if the required version isn't fetched 
automatically from Maven Central when you run maven, do the following:

	git clone https://github.com/IanDarwin/darwinsys-api
	cd darwinsys-api
	mvn package install

To test run it, just open the project in Eclipse (or import into IntelliJ or
other IDE) and run PdfShow, the main-program file.

To package just the program and its images (without the dependencies),
do `mvn package`.

To make a clickable runnable JAR file, run `mvn package assembly:single`
and you'll find a jar with dependencies in the target folder.
It'll be named something like _pdfshow-1.0.0-SNAPSHOT-jar-with-dependencies.jar_
You can run it with `java -jar` or click on it in Windows, macOS, 
or most *Nix windowed environments.

To make a full-blown, platform-specific installer, try the `mkinstaller` script.
Note that on Windows this has pre-requisites, which it will let you know about.

== Develop It

Fork the repo, clone your forked copy, make changes, test changes, send a pull request.

Q: Why didn't I use this for the drawing:

	PDPageContentStream contentStream = new PDPageContentStream(document, page);
	contentStream.setNonStrokingColor(Color.DARK_GRAY);
	contentStream.addRect(200, 650, 100, 100);

A: The problem is that it would be much harder (if not impossible) to implement Undo processing
when using that approach. Perhaps a later Save PDF function could
insert the GObjects into the PDF using this technique.

Q: Why not use the built-in contains for hit detection?
A: The GObject hierarchy is intentionally light-weight, not JComponent, and
it's gotta be the same amount of work.

== Credits

Program written by Ian Darwin of Rejminet Group Inc.
Contributions by a cast of thousands (someday).

PDF access (i.e., some of the heavy listing!) is done by 
https://pdfbox.apache.org/[Apache PDFBox] software.

Some icons from feathericons.com; a few simpler ones icons by Ian Darwin.
