= PdfShow

PdfShow is a simple Java Swing-based PDF viewer specifically for running slide shows.

It has many limitations compared with other tools (see the TODO file), due to 
its relative youth and, more importantly, its design goals.
These are laid out in the User Guide.

I will add more bells and whistles as time permits.

Pull requests will be gratefully accepted as long as they fit
within the general tone of the program - _minimalist, but functional._ 

== Using It

The program is intuitive and easy to use.
But there is documentation, in the `docs` folder.

== Build It

Download the repository from https://github.com/IanDarwin/pdfshow.

To test run it, just open the project in Eclipse (or import into IntelliJ or
other IDE) and run PdfShow, the main-program file.

To package just the program and its images (without the dependencies),
do `mvn package`.

To make a clickable runnable JAR file, run `mvn package assembly:single`
and you'll find a jar with dependencies in the target folder.
It'll be named something like _pdfshow-1.0.0-SNAPSHOT-jar-with-dependencies.jar_
You can run it with `java -jar` or click on it in Windows, macOS, 
or most *Nix windowed environments.

== Develop It

Fork the repo, clone your forked copy, make changes, test changes, send a pull request.

Q: Why didn't I use this for the drawing:

	PDPageContentStream contentStream = new PDPageContentStream(document, page);
	contentStream.setNonStrokingColor(Color.DARK_GRAY);
	contentStream.addRect(200, 650, 100, 100);

A: The problem is that it would be much harder (if not impossible) to implement Undo processing
when using that approach. Perhaps a later Save PDF function could
insert the GObjects into the PDF using this technique.

== Credits

Program by Ian Darwin of Rejminet Group Inc.

PDF access (i.e., some of the heavy listing!) is done by 
https://pdfbox.apache.org/[Apache PDFBox] software.

Icons from the Sun JLF Image Repository (c) Sun Micro.
Other icons Copyright(C) 1998 by Dean S. Jones
(formerly at gallant.com/icons.htm)
and a few icons by Ian Darwin.
