= PdfShow

PdfShow is a simple Swing-based PDF viewer for running slide shows.

Pdf access (i.e., the heavy listing!) is via https://pdfbox.apache.org/[Apache PDFBox].

I will add more bells and whistles as time permits.

Pull requests will be gratefully accepted as long as they fit within the general tone of the program - _minimalist, but functional._ 

== How-to

To test run it, just open the project in Eclipse (or import into IntelliJ or
other IDE) and run the PdfShow file.

To make a clickable runnable JAR file, run "mvn package assembly:single"
and you'll find a jar with dependencies in the target folder.
It'll be named something like _pdfshow-1.0.0-SNAPSHOT-jar-with-dependencies.jar_
You can run it with `java -jar` or click on it in Windows, Mac, or most *Nix windowed environments.

== Development

Fork the repo, clone your forked copy, make changes, test changes, send a pull request.

Why didn't I use this for the drawing:

	PDPageContentStream contentStream = new PDPageContentStream(document, page);
	contentStream.setNonStrokingColor(Color.DARK_GRAY);
	contentStream.addRect(200, 650, 100, 100);

The problem is that it would be much harder (if not impossible) to implement Undo processing
when using that approach. Perhaps a later Save PDF function could
insert the GObjects into the PDF using this technique.

== Credits

Program by Ian Darwin of Rejminet Group Inc.

Icons from the Sun JLF Image Repository (c) Sun Micro.
Other icons Copyright(C) 1998 by Dean S. Jones
(formerly at gallant.com/icons.htm)
and a few icons by Ian Darwin.
