= Release Notes

The release notes for current and past releases are in the github under releases.

== Implemented for next release.

Double-clicking on a Text box lets you edit the text, copy from it, etc.

== 1.1.0 Finders Keepers

* Implements the Find command, via CTRL/F, Edit->Find Menu, and a textfield in the toolbox.
The latter has a Search icon button that will repeat a search. 
Search will not find what's on the current page, and the found text isn't highlighted (yet?).
* The color picker has the half-dozen most common colors predefined, but you can still pick from a full-blown color chooser - this was in the previous release, but now: Picking a color no longer changes the color of existing objects.
* Better Progress Bar for seconds-long operations.

All binaries were corrected 2024-11-12 around 20:00 Eastern, a few days after the first binaries,
in order to fix an off-by-one that caused Find to miss some pages.

== UNRELEASED 1.0.6 (included in 1.1.0 above).

* Key shortcuts for graphics modes work in main window and in sidebar.
* All graphic tools (except highlighting) non-sticky, like Draw Text was in v1.0.5.
'Jump back to Select after text/draw' (sticky/non-sticky) is now an option, settable in the bottom section of the toolbox.
* Single letter commands to switch to t)ext, l)ine, o)val, etc - work with focus anywhere now.
* Bug fixes:
** Hitting ESC on Text dialog caused "uninitializedValue" text to appear.
** Moving the main window would cause it to appear microscopically small.
** Incorrect info in Help->About display.

== Version 1.0.5, 2024-09-21

v1.0.5 "Clock Watcher" is a minor revision; changes include:

* Break timer now in own "JFrame" window, works correctly.
* Scroll wheel support! I personally find this makes a huge
increase in usability when jumping back or ahead several slides at a time.
* Color picker bar in left panel w/ 7 pre-defined colors and a picker launcher
* CTRL/Z CMD/Z alias for Undo button, for undoing one or more draw commands
* Adds background images to the break timer (and you can add your own
without recompiling; see Help for how-to);
* Adds Delete Page function (non-persistent);
* Pointer mode pops back to View after adding Text item;
* Custom slide show (contiguous range only);
* Defaults to single monitor even on dual-monitor setups;
* Dialog to set line/draw thickness, with live preview
* Single letter commands to switch to t)ext, l)ine, o)val, etc - only with focus in display page, for now.
* Corrects several minor bugs, including:
** Color choice was static, not per-object
** View window came up wrong size if you have two monitors

=== Known Issues/Bugs

* Text draw dialog, hitting ESC leaves "Uninitialized Value" text.
* Drawn objects sometimes drawn in wrong places.
* Still can't select text or find text. Sorry.
* A weird buglet in the pdf library prevents drawing on pages where there is a JPEG image.
* Mac only: The color selector is drawn too large on some screens, but 
all the colors are at least clickable.

== Version 1.0.4, Unreleased (2023-05)

v1.0.4 "Double Header" is the first release supporting two monitors, as conventional slide show programs do.
The "control" screen has the control buttons and the "view" screen goes full-screen on the second monitor.
This is beta and has not been extensively tested, so comments would be welcome!

Of course it still works on a single monitor.

I suspect the #1 feature request will be the ability to choose which monitor to have which screen on.
My first idea is to just open the control screen on whichever screen you start the program on,
and the view screen on the other. Other ideas?
