= `PdfShow`
:author: Ian Darwin

`PdfShow` is a simple Java Swing-based PDF viewer specifically for running slide shows.
If you want to pre-draw fancy diagrams, and save them for each time you present your
slide deck, this is not for you. Use Adobe Reader DC, PDF Annotator, or some other
fancier tool.
It you like to scribble all over your slides each time you run your course,
to make the slides come alive, then `PdfShow` may be right for you.

This program is free software and may be copied for use without fee.
The source code is https://github.com/IanDarwin/pdfshow[available on my GitHub repository] 
if you are a developer and would like to improve it.

== Installing it

Downloads are occasionally released on my https://github.com/IanDarwin/pdfshow/releases[GitHub page].

If you already have a Java JDK installed, 
and either have `java` on your path or want to click on a Jar file to run it
or invoke the program with a batch file / shell script, 
pick the `pdfshow`-x.x.x-with-dependencies.jar.

If you'd rather a full installer, pick the `pdfshow`-x.x.x.dmg file for your macOS system
or the `pdfshow`-x.x.x.msi for your Windows box.
I plan to build an RPM and/or DEB for Linux later.

== Using It

This is intended for slide shows, which are almost always in "landscape mode"
(oriented like a laptop or computer monitor, not upright like a smartphone).
Slide decks will be scaled to fit your monitor, so book-style documents
(portrait mode documents) will appear unusually wide, though still readable.
There is a code issue (https://github.com/IanDarwin/pdfshow/issues/7[Issue#7]) that will improve the scaling.

Like most GUI tools, you can open a file either by passing it on the command line,
via the `File->Open` menu, or via `CTRL`/`CMD`-O.
You can have multiple files open, using the tab selecter at the top.

=== Navigation

You can move around within a file using:

* The scroll bar at the right side of the current tab;
* The `Up` and `Down` buttons in the nav box;
* The `Begin` and `End` buttons in the nav box (first and last page).
* Typing a given page number in the page number box in the middle of the nav box;
_Note that this is a programmer's tool so pages number from 0 to n-1_.
* Ensuring the mouse is in the window, and using:
** `DownArrow`, `j`, `SPACE`, or `RETURN` to move to the next page;
** `UpArrow`, `k`, `DELETE`, or `BACKSPACE` to move to the previous page.

=== Drawing

There are multiple draw tool icons in the toolbox. Each of these
only has effect once, that is, you have to click the Line button
a second time to draw a second line.
I may add an option later to remove this behaviour.

The toolbox has icons for straight line, polyline and rectangle.
Each of these will rubber-band as you draw it, like most draw programs.
The Text icon currently pops up a dialog for the text, but that will
hopefully be simplified soon.
Each graphic object that you attach to a page will stay with that page
until you close the file or exit the application.
They are not saved, since that goes against the "make your slides come alive" mantra.
But I am open to well-reasoned arguments in favor of saving them into the PDF,
especially if accompanied by a "pull request" containing working code.

The Undo button removes the most-recently added graphic each time it's pressed.
The Trash icon removes *all* graphics from the current page.

== Credits

Program by Ian Darwin of Rejminet Group Inc.

PDF access (i.e., some of the heavy listing!) is done by 
https://pdfbox.apache.org/[Apache PDFBox] software.

Most icons from feathericons.com, and a simpler ones icons by Ian Darwin.
