= PdfShow
:author: Ian Darwin

PdfShow is a simple Java Swing-based PDF viewer specifically for running slide shows.
If you want to pre-draw fancy diagrams, and save them for each time you present your
slide deck, this is not for you. Use Adobe Reader DC, PDF Annotator, or some other
fancier tool.
It you like to scribble all over your slides each time you run your course,
to make the slides come alive, then you find that PdfShow may be right for you.

This program is free software and may be copied for use without fee.
The source code is https://github.com/IanDarwin/pdfshow[available on my GitHub repository] 
if you are a developer and would like to improve it.

== Installing it

Downloads are occasionally released on my https://github.com/IanDarwin/pdfshow[GitHub page].

If you're already a heavy Java user with a JDK installed, 
and either have `java` on your path or want to click on a Jar file to run it
or invoke the program with a batch file / shell script, 
pick the pdfshow-1.x.x-with-dependencies.jar.

If you'd rather a full installer, pick the pdfshow-1.x.x.dmg file for your macOS system
or the pdfshow-1.x.x.msi for your Windows box.
I might build an RPM or DEB for Linux later.

== Using It

Like most GUI tools, you can open a file either by passing it on the command line 
or via the File->Open menu.
You can have multiple files open, using the tab selecter at the top.

=== Navigation

You can move around within a file using:

* The scroll bar at the right side of the current tab;
* The `Up` and `Down` buttons in the nav box;
* The `Begin` and `End` buttons in the nav box (first and last page).
* Typing a given page number in the page number box in the middle of the nav box;
_Note that this is a programmer's tool so pages number from 0 to n-1_.
* Ensuring the mouse is in the window, and using:
** `DownArrow`, `j`, `SPACE`, or `RETURN` to move to the next page;
** `UpArrow`, `k`, `DELETE`, or `BACKSPACE` to move to the previous page.

=== Drawing

The toolbox has icons for straight line, polyline and rectangle.
Each of these will rubber-band as you draw it, like most draw programs.
The Text icon currently pops up a dialog for the text, but that will
hopefully be simplified soon.
Each graphic object that you attach to a page will stay with that page
until you close the file or exit the application.
They are not saved, since that goes against the "make your slides come alive" mantra.
But I am open to well-reasoned arguments in favor of saving them into the PDF,
especially if accompanied by a "pull request" containing working code.

== Credits

Program by Ian Darwin of Rejminet Group Inc.

PDF access (i.e., some of the heavy listing!) is done by 
https://pdfbox.apache.org/[Apache PDFBox] software.

Icons from the Sun JLF Image Repository (c) Sun Micro.
Other icons Copyright(C) 1998 by Dean S. Jones
(formerly at gallant.com/icons.htm)
and a few icons by Ian Darwin.
