= `PdfShow` Usage
:author: Ian Darwin

`PdfShow` is a simple Java Swing-based PDF viewer specifically for running slide shows.
If you want to pre-draw fancy diagrams, and save them for each time you present your
slide deck, this is not for you. 
Use Adobe Reader DC, PDF Annotator, or some other fancier tool.
And if your presentation skills depend on blurry transitions or zippy little animations,
just present in KeyNote, LibreOffice or PowerPoint.
However, if you like to scribble all over the slides in your PDF slide deck each time you run your course,
to make the slides come alive, then `PdfShow` may be right for you.

This program is free software and may be copied for use without fee.
The source code is https://github.com/IanDarwin/pdfshow[available on my GitHub repository];
if you are a developer and would like to improve it, Github pull requests are welcome.

== Installing it

Downloads are occasionally released on my https://github.com/IanDarwin/pdfshow/releases[GitHub page].

If you already have a Java JDK installed, 
and either have `java` on your path or want to click on a Jar file to run it
or invoke the program with a batch file / shell script, 
pick the `pdfshow`-x.x.x-with-dependencies.jar.

If you'd rather a full installer, pick the `pdfshow`-x.x.x.dmg file for your macOS system
or the `pdfshow`-x.x.x.msi for your Windows box.
I plan to build an RPM and/or DEB for Linux later.

== Using It

This is intended for slide shows, which are almost always in "landscape mode"
(oriented like a laptop or computer monitor, not upright like a smartphone).
Slide decks will be scaled to fit your monitor, so book-style documents
(portrait mode documents) will appear unusually wide, though still readable.
There is a code issue (https://github.com/IanDarwin/pdfshow/issues/7[Issue#7]) that will improve the scaling.

Like most GUI tools, you can open a file either by passing it on the command line,
via the `File->Open` menu, or via `CTRL`/`CMD`-O.
You can have multiple files open, using the tab selecter at the top.

=== Navigation

You can move around within a file using:

* The scroll bar at the right side of the current tab;
* The `Up` and `Down` buttons in the nav box;
* The `Begin` and `End` buttons in the nav box (first and last page).
* Typing a given page number in the page number box in the middle of the nav box;
* Ensuring the mouse is in the window, and using these shortcuts (not all work on all platforms):
** `DownArrow`, `j`, `SPACE`, or `RETURN` to move to the next page;
** `UpArrow`, `k`, `DELETE`, or `BACKSPACE` to move to the previous page.

=== Drawing

There are multiple draw tool icons in the toolbox. 
// Each of these
// only has effect once, that is, you have to click the Line button
// a second time to draw a second line.
These buttons are sticky, that is, to draw two lines, click the line icon, draw one line, then you can draw another without re-clicking the line icon.
I may add an option later to control this behaviour.

The toolbox has icons for straight line, polyline and rectangle.
Each of these will rubber-band as you draw it, like most draw programs.
The Text icon currently pops up a dialog for the text, but that will
hopefully be simplified soon.
Each graphic object that you attach to a page will stay with that page
until you close the file or exit the application.
They are not saved, since that goes against the "make your slides come alive" mantra.
But I am open to well-reasoned arguments in favor of saving them into the PDF,
especially if accompanied by a "pull request" containing working code.

The Undo button removes the most-recently added graphic each time it's pressed.
To delete an arbitrary graphic, click the `Select` icon then select the item
you want to get rid of, then either use the `Delete` key (if it's not mapped to
VK_UP as it is on some systems) or use the `Edit->Delete Selected` menu item.
The Trash Can icon is the most drastic: it removes *all* graphics from the current page.

=== Slide Show Mode

There are two modes for auto-presenting, which I call "across" and "down".
Across mode goes across all the tabs, showing the current slide from each.
This might be useful when, for example, the training company provides a standard
slide deck that you have to use, but you want a show alternating between their opening slide
and your own informational slide during the pre-class period.
That's the use case I designed it for, but your mileage may vary.

"Down" mode is normal slide show mode - run through all the slides in one tab.

For both modes, there is a single "Interval time" setting, which controls the speed
of both modes, and takes effect on the next slide if changed during a show.
The "Stop slide" button is at the bottom left, below the Settings.

=== Settings

There is a Settings icon in the lower part of the left-hand pane;
this pops up a dialog to control
various settings, such as the font and color for drawing,
the speed of slide shows, etc.
 
The "Open at last-used page" is for the case where a slideshow takes more than one day,
and your computer gets shut down overnight; in the morning when you open the file again
it will resume where you left off. This behaviour is true by default.

== Credits

Program by Ian Darwin of Rejminet Group Inc.

PDF access (i.e., some of the heavy listing!) is done by 
https://pdfbox.apache.org/[Apache PDFBox] software.

Some icons from feathericons.com, and a simpler ones icons by Ian Darwin.
